name: Docker Publish

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-publish.yml'
      - '*/*.go'
      - 'main.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  check_commit:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.compare.outputs.should_skip }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag SHA and compare with current commit
        id: compare
        run: |
          # Fetch all tags from remote
          git fetch --tags origin

          # Get the SHA of the latest tag
          LATEST_TAG_SHA=$(git rev-list --tags --max-count=1)

          # Get the SHA of the current HEAD commit that triggered the workflow
          CURRENT_COMMIT_SHA=${{ github.sha }}

          echo "Latest tag SHA: $LATEST_TAG_SHA"
          echo "Current commit SHA: $CURRENT_COMMIT_SHA"

          # Compare the SHAs
          if [ "$LATEST_TAG_SHA" = "$CURRENT_COMMIT_SHA" ]; then
            echo "::set-output name=should_skip::true"
          else
            echo "::set-output name=should_skip::false"
          fi

  build-and-push:
    runs-on: ubuntu-latest
    needs: check_commit
    if: needs.check_commit.outputs.skip == 'false'
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            jonathanlazaro1/goes-back
          tags: |
            type=sha

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to dhi.io
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: dhi.io

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
